name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
      - uses: actions/setup-node@v4.0.4
        with: 
          node-version: 18.18.0

      - name: Build Project
        run: npm run build:ssr

      - name: turn into zip
        run: zip -r your-app.zip .  
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'bestmoviesinc'
          environment_name: 'bestmoviesinc-dev2'
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: your-app.zip
